services:
  opensearch:
    container_name: eclaire-os
    image: opensearchproject/opensearch:2.13.0
    environment:
      - plugins.security.disabled=true
      - discovery.type=single-node
      - OPENSEARCH_INITIAL_ADMIN_PASSWORD=Ecl@ire2025
      #- DISABLE_SECURITY_PLUGIN=true   
      - OPENSEARCH_JAVA_OPTS=-Xms192m -Xmx192m
    networks:
      - eclaire
    volumes:
      - type: volume
        source: opensearch_data
        target: /usr/share/opensearch/data
    ports:
      - "9202:9200"    
  dashboards:
    container_name: eclaire-os-dash
    image: opensearchproject/opensearch-dashboards:2.13.0
    environment:
      - OPENSEARCH_HOSTS=http://eclaire-os:9202
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    networks:
      - eclaire
    depends_on:
      - opensearch
    ports:
      - "5602:5602"  
networks:
  eclaire:
    driver: bridge
volumes:
  opensearch_data:
