export const CTIS_COLUMNS = [
  { header: 'Numéro CTIS', key: 'numero_ctis' },
  { header: 'Reglementation_Code', key: 'reglementation_code' },
  { header: 'publication_eclaire', key: 'publication_eclaire' },
  { header: 'Etat', key: 'etat' },
  { header: 'Statut_recrutement', key: 'statut_recrutement' },
  { header: 'date_debut_recrutement', key: 'date_debut_recrutement' },
  { header: 'date_fin_recrutement', key: 'date_fin_recrutement' },
  { header: 'contact_public_nom', key: 'contact_public_nom' },
  { header: 'contact_public_prenom', key: 'contact_public_prenom' },
  { header: 'contact_public_courriel', key: 'contact_public_courriel' },
  { header: 'contact_public_telephone', key: 'contact_public_telephone' },
  { header: 'numero_nct', key: 'numero_nct' },
  { header: 'numero_isrctn', key: 'numero_isrctn' },
  { header: 'numero_utn', key: 'numero_utn' },
  { header: 'objectifs', key: 'objectifs' },
  { header: 'resume', key: 'resume' },
  { header: 'duree_participation', key: 'duree_participation' },
  { header: 'tranches_age', key: 'tranches_age' },
  { header: 'sexe', key: 'sexe' },
  { header: 'groupe_sujets', key: 'groupes_sujet' },
  { header: 'population_recrutement', key: 'population_recrutement' },
  { header: 'description_urgence', key: 'description_urgence' },
  { header: "Critères d'éligibilité", key: "criteres_eligibilite" },
  { header: "Critères de jugement", key: "criteres_jugement" },
  { header: 'Site_organisme', key: 'sites.organisme' },
  { header: 'Site_adresse', key: 'sites.adresse' },
  { header: 'Site_ville', key: 'sites.ville' },
  { header: 'Site_code_postal', key: 'sites.code_postal' },
  { header: 'Site_titre', key: 'sites.titre' },
  { header: 'Site_nom', key: 'sites.nom' },
  { header: 'Site_prenom', key: 'sites.prenom' },
  { header: 'Site_courriel', key: 'sites.courriel' },
  { header: 'Site_téléphone', key: 'sites.telephone' },
  { header: 'Site_service', key: 'sites.service' },
  { header: 'organisme_nom', key: 'organisme_nom' },
  { header: 'organisme_adresse', key: 'organisme_adresse' },
  { header: 'organisme_code_postal', key: 'organisme_code_postal' },
  { header: 'organisme_pays', key: 'organisme_pays' },
  { header: 'organisme_ville', key: 'organisme_ville' },
  { header: 'contact_nom', key: 'contact_nom' },
  { header: 'contact_prenom', key: 'contact_prenom' },
  { header: 'contact_telephone', key: 'contact_telephone' },
  { header: 'contact_courriel', key: 'contact_courriel' },
  { header: 'titre recherche', key: 'titre' },
  { header: 'intervention_faible', key: 'intervention_faible' },
  { header: 'phase_recherche', key: 'phase_recherche' },
  { header: 'domaine_therapeutique', key: 'domaine_therapeutique' },
  { header: 'pathologies_maladies_rares', key: 'pathologies_maladies_rares' },
  { header: 'informations_meddra', key: 'informations_meddra' },
  { header: 'portee_recherche', key: 'portee_recherche' },
  { header: 'taille_etude', key: 'taille_etude' },
  { header: 'date_fin_etude', key: 'date_fin_etude' },
  { header: 'historique', key: 'historique' },
  { header: 'dates_avis_favorable_ms_mns', key: 'dates_avis_favorable_ms_mns' },
  { header: 'pays_concernés', key: 'pays_concernes' }
]