										 	  	 	 	 								
export const JARDE_COLUMNS = [
    { header: 'Numéro', key: 'numero' },
    { header: 'Numéro national', key: 'numero_national' },
    { header: 'Reglementation_Code', key: 'reglementation_code' },
    { header: 'Etat', key: 'etat' },
    { header: 'publication_eclaire', key: 'publication_eclaire' },
    { header: 'Statut_recrutement', key: 'statut_recrutement' },
    { header: 'date_debut_recrutement', key: 'date_debut_recrutement' },
    { header: 'date_fin_recrutement', key: 'date_fin_recrutement' },
    { header: 'contact_public_nom', key: 'contact_public_nom' },
    { header: 'contact_public_prenom', key: 'contact_public_prenom' },
    { header: 'contact_public_courriel', key: 'contact_public_courriel' },
    { header: 'contact_public_telephone', key: 'contact_public_telephone' },
    { header: 'numero_nct', key: 'numero_nct' },
    { header: 'numero_isrctn', key: 'numero_isrctn' },
    { header: 'numero_utn', key: 'numero_utn' },
    { header: 'numero_libre', key: 'numero_libre' },
    { header: 'objectifs', key: 'objectifs' },
    { header: 'resume', key: 'resume' },
    { header: 'duree_participation', key: 'duree_participation' },
    { header: 'participants_tranches_age', key: 'participants_tranches_age' },
    { header: 'participants_sexe', key: 'participants_sexe' },
    { header: 'participants_groupe_sujets', key: 'participants_groupe_sujets' },
    { header: 'participants_population_vulnerable', key: 'participants_population_vulnerable' },
    { header: "Critères d'éligibilité", key: 'criteres_eligibilite' },
    { header: 'Critères de jugement', key: 'criteres_jugement' },
    { header: 'Site investigateur_organisme', key: 'sites_investigateurs.organisme' },
    { header: 'Site investigateur_adresse', key: 'sites_investigateurs.adresse' },
    { header: 'Site investigateur_ville', key: 'sites_investigateurs.ville' },
    { header: 'Site investigateur_code_postal', key: 'sites_investigateurs.code_postal' },
    { header: 'Site investigateur_titre', key: 'sites_investigateurs.titre_investigateur' },
    { header: 'Site investigateur_nom', key: 'sites_investigateurs.nom' },
    { header: 'Site investigateur_prenom', key: 'sites_investigateurs.prenom' },
    { header: 'Site investigateur_courriel', key: 'sites_investigateurs.courriel' },
    { header: 'Site investigateur_téléphone', key: 'sites_investigateurs.telephone' },
    { header: 'Site investigateur_service', key: 'sites_investigateurs.service' },
    { header: 'type_promoteur', key: 'type_promoteur' },
    { header: 'deposant_nom', key: 'deposant_nom' },
    { header: 'deposant_prenom', key: 'deposant_prenom' },
    { header: 'deposant_courriel', key: 'deposant_courriel' },
    { header: 'deposant_organisme', key: 'deposant_organisme' },
    { header: 'deposant_adresse', key: 'deposant_adresse' },
    { header: 'deposant_siret', key: 'deposant_siret' },
    { header: 'deposant_code_postal', key: 'deposant_code_postal' },
    { header: 'deposant_ville', key: 'deposant_ville' },
    { header: 'deposant_pays', key: 'deposant_pays' },
    { header: 'is_mandataire', key: 'is_mandataire' },
    { header: 'promoteur_nom', key: 'promoteur_nom' },
    { header: 'promoteur_prenom', key: 'promoteur_prenom' },
    { header: 'promoteur_email', key: 'promoteur_email' },
    { header: 'promoteur_organisme', key: 'promoteur_organisme' },
    { header: 'promoteur_adresse', key: 'promoteur_adresse' },
    { header: 'promoteur_siret', key: 'promoteur_siret' },
    { header: 'promoteur_code_postal', key: 'promoteur_code_postal' },
    { header: 'promoteur_ville', key: 'promoteur_ville' },
    { header: 'promoteur_pays', key: 'promoteur_pays' },
    { header: 'mandataire_nom', key: 'mandataire_nom' },
    { header: 'mandataire_prenom', key: 'mandataire_prenom' },
    { header: 'mandataire_email', key: 'mandataire_email' },
    { header: 'mandataire_organisme', key: 'mandataire_organisme' },
    { header: 'mandataire_adresse', key: 'mandataire_adresse' },
    { header: 'mandataire_siret', key: 'mandataire_siret' },
    { header: 'mandataire_code_postal', key: 'mandataire_code_postal' },
    { header: 'mandataire_ville', key: 'mandataire_ville' },
    { header: 'mandataire_pays', key: 'mandataire_pays' },
    { header: 'investigateur', key: 'investigateur' },
    { header: 'titre recherche', key: 'titre_recherche' },
    { header: 'domaine_therapeutique', key: 'domaine_therapeutique' },
    { header: 'taille_etude', key: 'taille_etude' },
    { header: 'compétences', key: 'etcompetencesat' },
    { header: 'caracteristiques_recherche', key: 'caracteristiques_recherche' },
    { header: 'recherche_ancillaire_ou_extension', key: 'recherche_ancillaire_ou_extension' },
    { header: 'qualification_recherche', key: 'qualification_recherche' },
    { header: 'date_soumission', key: 'date_soumission' },
    { header: 'date_creation_etude', key: 'date_creation_etude' },    
    { header: 'date_previsionnelle_fin_etude', key: 'date_previsionnelle_fin_etude' },
    { header: 'historique', key: 'historique' },
    { header: 'dates_avis_favorable_ms_mns', key: 'dates_avis_favorable_ms_mns' },
]