export enum SecondaryAge {
  PRETERM_NEWBORN = 'PRETERM_NEWBORN',
  ZERO_TWENTY_SEVEN_DAYS = '0_27_DAYS',
  TWENTY_EIGHT_DAYS_TWENTY_THREE_MONTHS = '28_DAYS_23_MONTHS',
  TWO_FIVE_YEARS = '2_5_YEARS',
  SIX_ELEVEN_YEARS = '6_11_YEARS',
  TWELVE_SEVENTEEN_YEARS = '12_17_YEARS',
  SIXTY_FIVE_EIGHTY_FOUR_YEARS = '65_84_YEARS',
  EIGHTY_FIVE_PLUS_YEARS = '85_PLUS_YEARS',
}
